GET http://localhost:8080/user

###

# Post Admin
POST http://localhost:8080/register
Content-Type: application/json

{
	"username": "arganaphangquestian",
	"name": "Argana Phangquestian",
	"email": "arganaadmin@mail.com",
	"password": "argana123"
}

###

# Post User
POST http://localhost:8080/register
Content-Type: application/json

{
	"username": "arganaphangquestian",
	"name": "Argana Phangquestian",
	"email": "argana@mail.com",
	"password": "argana123",
	"referral": "test123"
}